import type { TypographyTheme, TypographyThemeKey } from "../types/typography";

export const typographyThemes: Record<TypographyThemeKey, TypographyTheme> = {
  pixel: {
    key: "pixel",
    label: "Pixel",
    fontFamily: "'Press Start 2P', monospace",
    fontSize: 14,
    subFontSize: 11,
    letterSpacing: "0.05em",
    textTransform: "uppercase",
    defaultTextColor: "#ffffff",
    defaultSubColor: "#39ff14",
    googleFont: "Press+Start+2P",
  },
  terminal: {
    key: "terminal",
    label: "Terminal",
    fontFamily: "'Share Tech Mono', monospace",
    fontSize: 22,
    subFontSize: 17,
    letterSpacing: "0.08em",
    textTransform: "lowercase",
    defaultTextColor: "#39ff14",
    defaultSubColor: "#00ff9f",
    googleFont: "Share+Tech+Mono",
  },
  cyberpunk: {
    key: "cyberpunk",
    label: "Cyberpunk",
    fontFamily: "'Orbitron', sans-serif",
    fontSize: 18,
    subFontSize: 14,
    letterSpacing: "0.15em",
    textTransform: "uppercase",
    defaultTextColor: "#00f0ff",
    defaultSubColor: "#ff006e",
    googleFont: "Orbitron",
  },
  handwritten: {
    key: "handwritten",
    label: "Handwritten",
    fontFamily: "'Caveat', cursive",
    fontSize: 30,
    subFontSize: 24,
    letterSpacing: "0.02em",
    textTransform: "none",
    defaultTextColor: "#ffffff",
    defaultSubColor: "#ffd700",
    googleFont: "Caveat",
  },
  "retro-arcade": {
    key: "retro-arcade",
    label: "Retro Arcade",
    fontFamily: "'Bungee', cursive",
    fontSize: 20,
    subFontSize: 15,
    letterSpacing: "0.1em",
    textTransform: "uppercase",
    defaultTextColor: "#ffdd00",
    defaultSubColor: "#ff4500",
    googleFont: "Bungee",
  },
  monospace: {
    key: "monospace",
    label: "Monospace",
    fontFamily: "'Roboto Mono', monospace",
    fontSize: 20,
    subFontSize: 16,
    letterSpacing: "0.04em",
    textTransform: "none",
    defaultTextColor: "#e2e8f0",
    defaultSubColor: "#94a3b8",
    googleFont: "Roboto+Mono",
  },
  vaporwave: {
    key: "vaporwave",
    label: "Vaporwave",
    fontFamily: "'Righteous', cursive",
    fontSize: 22,
    subFontSize: 17,
    letterSpacing: "0.12em",
    textTransform: "uppercase",
    defaultTextColor: "#ff71ce",
    defaultSubColor: "#b967ff",
    googleFont: "Righteous",
  },
  minimalist: {
    key: "minimalist",
    label: "Minimalist",
    fontFamily: "'DM Sans', sans-serif",
    fontSize: 24,
    subFontSize: 18,
    letterSpacing: "0.2em",
    textTransform: "uppercase",
    defaultTextColor: "#ffffff",
    defaultSubColor: "#888888",
    googleFont: "DM+Sans",
  },
  hacker: {
    key: "hacker",
    label: "Hacker",
    fontFamily: "'Source Code Pro', monospace",
    fontSize: 18,
    subFontSize: 14,
    letterSpacing: "0.06em",
    textTransform: "lowercase",
    defaultTextColor: "#00ff41",
    defaultSubColor: "#008f11",
    googleFont: "Source+Code+Pro",
  },
  anime: {
    key: "anime",
    label: "Anime",
    fontFamily: "'Fredoka One', cursive",
    fontSize: 26,
    subFontSize: 20,
    letterSpacing: "0.06em",
    textTransform: "capitalize",
    defaultTextColor: "#ffffff",
    defaultSubColor: "#ff6eb4",
    googleFont: "Fredoka+One",
  },
};

export const DEFAULT_TYPOGRAPHY_KEY: TypographyThemeKey = "terminal";
